# SPDX-FileCopyrightText: 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Windows-Qt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        archives: qtbase qttools

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -T ClangCL -DENABLE_QT_GUI=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Deploy
      run: |
        mkdir upload
        move build/Release/shadPS4.exe upload
        move build/translations upload
        windeployqt --dir upload upload/shadPS4.exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: shadps4-win64-qt
        path: upload
